apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: 055968157196.dkr.ecr.ap-south-1.amazonaws.com/pythonregistry:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-12-07T08:04:22Z"
  labels:
    app: python
  name: deploy
  namespace: default
  resourceVersion: "4706"
  selfLink: /api/v1/namespaces/default/services/mydeploy
  uid: sdjsbcjscbdbc-dcdb-dcdc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: python
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}