# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login to docker hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSSWORD }}

      run: |
       docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build docker image
      run: |
        docker build . -t akashacharya/pythonimage 
        echo " Docker image has been built"
    - name: push the docker image to docker hub
      run: |
        docker push akashacharya/pythonimage


    
